# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/SOC/PYNQ-Z2/Project/04-PS_HELLO/PS_HELLO.srcs/sources_1/bd/ps_hello/ip/ps_hello_processing_system7_0_3/ps_hello_processing_system7_0_3.xci
# IP: The module: 'ps_hello_processing_system7_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SOC/PYNQ-Z2/Project/04-PS_HELLO/PS_HELLO.srcs/sources_1/bd/ps_hello/ip/ps_hello_processing_system7_0_3/ps_hello_processing_system7_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_hello_processing_system7_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/SOC/PYNQ-Z2/Project/04-PS_HELLO/PS_HELLO.srcs/sources_1/bd/ps_hello/ip/ps_hello_processing_system7_0_3/ps_hello_processing_system7_0_3.xci
# IP: The module: 'ps_hello_processing_system7_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SOC/PYNQ-Z2/Project/04-PS_HELLO/PS_HELLO.srcs/sources_1/bd/ps_hello/ip/ps_hello_processing_system7_0_3/ps_hello_processing_system7_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_hello_processing_system7_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
