# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ps_hello/ps_hello.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_hello || ORIG_REF_NAME==ps_hello} -quiet] -quiet

# IP: bd/ps_hello/ip/ps_hello_processing_system7_0_3/ps_hello_processing_system7_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_hello_processing_system7_0_3 || ORIG_REF_NAME==ps_hello_processing_system7_0_3} -quiet] -quiet

# XDC: bd/ps_hello/ps_hello_ooc.xdc
