# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/SOC/PYNQ-Z2/Project/03-PL_HDMI_OUT/PL_HDMI_OUT.srcs/sources_1/ip/video_clock/video_clock.xci
# IP: The module: 'video_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SOC/PYNQ-Z2/Project/03-PL_HDMI_OUT/PL_HDMI_OUT.srcs/sources_1/ip/video_clock/video_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/SOC/PYNQ-Z2/Project/03-PL_HDMI_OUT/PL_HDMI_OUT.srcs/sources_1/ip/video_clock/video_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/SOC/PYNQ-Z2/Project/03-PL_HDMI_OUT/PL_HDMI_OUT.srcs/sources_1/ip/video_clock/video_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/SOC/PYNQ-Z2/Project/03-PL_HDMI_OUT/PL_HDMI_OUT.srcs/sources_1/ip/video_clock/video_clock.xci
# IP: The module: 'video_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SOC/PYNQ-Z2/Project/03-PL_HDMI_OUT/PL_HDMI_OUT.srcs/sources_1/ip/video_clock/video_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/SOC/PYNQ-Z2/Project/03-PL_HDMI_OUT/PL_HDMI_OUT.srcs/sources_1/ip/video_clock/video_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/SOC/PYNQ-Z2/Project/03-PL_HDMI_OUT/PL_HDMI_OUT.srcs/sources_1/ip/video_clock/video_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
