# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/SOC/PYNQ-Z2/Project/05-FirstDesign/first_zynq_design.srcs/sources_1/bd/zynq_system_design/ip/zynq_system_design_processing_system7_0_1/zynq_system_design_processing_system7_0_1.xci
# IP: The module: 'zynq_system_design_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SOC/PYNQ-Z2/Project/05-FirstDesign/first_zynq_design.srcs/sources_1/bd/zynq_system_design/ip/zynq_system_design_processing_system7_0_1/zynq_system_design_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_system_design_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/SOC/PYNQ-Z2/Project/05-FirstDesign/first_zynq_design.srcs/sources_1/bd/zynq_system_design/ip/zynq_system_design_processing_system7_0_1/zynq_system_design_processing_system7_0_1.xci
# IP: The module: 'zynq_system_design_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SOC/PYNQ-Z2/Project/05-FirstDesign/first_zynq_design.srcs/sources_1/bd/zynq_system_design/ip/zynq_system_design_processing_system7_0_1/zynq_system_design_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_system_design_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
